### PR TITLE
Meta: update the URL for the common deploy.sh script

### PR DESCRIPTION
**Pull request by foolip**
Part of https://github.com/whatwg/whatwg.org/issues/71.

Also require the dist to be Trusty.

### CODE REVIEW

**Comment by annevk** [comment]
This one failed for some reason. Restarted.

**Comment by annevk** [comment]
Still fails, not sure why.

**Comment by foolip** [comment]
I also don't understand it. I think it's failing in the SERVICE_WORKER_SHA step, but it works locally. Maybe there's some rate limiting going on and this job is running on a machine that's being blocked?

**Comment by foolip** [comment]
https://github.com/whatwg/compat/pull/84 is also failing in the same way. I'll add in some extra logging to debug in this PR.

**Comment by foolip** [comment]
The problem was probably rate limiting, fixed in https://github.com/whatwg/whatwg.org/pull/74

**Pull request closed without merging**
